export type AttributeAssignmentOperator = '' | ':' | '=' | '+' | '-';

export interface AttributeAssignment {
  readonly name: string;
  readonly operator: AttributeAssignmentOperator;
  readonly expression: string;
}

const attributeAssignmentPattern = /([\p{L}_]+)\s*([:+=-]?)\s*((?:\d*[dD]\d+(?:[*/]\d+)*|-?\d+))/gu;

const coc7AttributeAliases: Readonly<Record<string, string>> = {
  str: '力量',
  siz: '体型',
  体形: '体型',
  con: '体质',
  dex: '敏捷',
  app: '外貌',
  外表: '外貌',
  edu: '教育',
  知识: '教育',
  int: '智力',
  灵感: '智力',
  pow: '意志',
  luck: '幸运',
  幸运值: '幸运',
  运气: '幸运',
  db: 'DB',
  伤害加值: 'DB',
  build: '体格',
  mov: '移动力',
  移动速度: '移动力',
  移速: '移动力',
  ar: '护甲',
  armor: '护甲',
  装甲: '护甲',
  san: '理智',
  san值: '理智',
  理智值: '理智',
  理智点数: '理智',
  心智: '理智',
  心智点数: '理智',
  hp: '生命值',
  生命: '生命值',
  体力: '生命值',
  血量: '生命值',
  耐久值: '生命值',
  hpmax: '生命值上限',
  生命上限: '生命值上限',
  体力上限: '生命值上限',
  血量上限: '生命值上限',
  耐久值上限: '生命值上限',
  mp: '魔法值',
  魔法: '魔法值',
  魔力: '魔法值',
  魔力值: '魔法值',
  mpmax: '魔法值上限',
  魔法上限: '魔法值上限',
  蓝量上限: '魔法值上限',
  信誉: '信用评级',
  信用: '信用评级',
  信誉度: '信用评级',
  cr: '信用评级',
  魅惑: '取悦',
  快速交谈: '话术',
  威吓: '恐吓',
  辩论: '说服',
  议价: '说服',
  演讲: '说服',
  语言: '外语',
  其他语言: '外语',
  躲藏: '潜行',
  跟踪: '追踪',
  侦察: '侦查',
  倾听: '聆听',
  唇语: '读唇',
  图书馆: '图书馆使用',
  图书馆利用: '图书馆使用',
  攀岩: '攀爬',
  攀登: '攀爬',
  藏匿: '妙手',
  盗窃: '妙手',
  开锁: '锁匠',
  撬锁: '锁匠',
  钳工: '锁匠',
  电器维修: '电气维修',
  电工: '电气维修',
  机器维修: '机械维修',
  机修: '机械维修',
  电脑使用: '计算机使用',
  计算机: '计算机使用',
  电脑: '计算机使用',
  领航: '导航',
  驾驶: '汽车驾驶',
  汽车: '汽车驾驶',
  开车: '汽车驾驶',
  驾车: '汽车驾驶',
  驯养: '动物驯养',
  驯兽: '动物驯养',
  重型操作: '操作重型机械',
  重型机械: '操作重型机械',
  重型: '操作重型机械',
  重机: '操作重型机械',
  斧头: '斧',
  斧子: '斧',
  电锯: '链锯',
  油锯: '链锯',
  链枷: '连枷',
  绞具: '绞索',
  剑术: '剑',
  火器: '射击',
  枪械: '射击',
  弓: '射击:弓',
  弓术: '射击:弓',
  弓箭: '射击:弓',
  手枪: '射击:手枪',
  重武器: '射击:重武器',
  火焰喷射器: '射击:火焰喷射器',
  机枪: '射击:机枪',
  步枪: '射击:步霰',
  霰弹枪: '射击:步霰',
  步霰: '射击:步霰',
  散弹枪: '射击:步霰',
  冲锋枪: '射击:冲锋枪',
  躲闪: '闪避',
  火炮: '炮术',
  医疗: '医学',
  心理分析: '精神分析',
  律法: '法律',
  自然: '博物学',
  自然学: '博物学',
  自然史: '博物学',
  cm: '克苏鲁神话',
  克苏鲁: '克苏鲁神话',
};

const dnd5eAttributeAliases: Readonly<Record<string, string>> = {
  str: '力量',
  strength: '力量',
  dex: '敏捷',
  dexterity: '敏捷',
  con: '体质',
  constitution: '体质',
  int: '智力',
  intelligence: '智力',
  wis: '感知',
  wisdom: '感知',
  cha: '魅力',
  charisma: '魅力',
  pb: '熟练',
  hp: 'HP',
  health: 'HP',
  hpmax: 'MaxHP',
  maxhp: 'MaxHP',
  temphp: 'TempHP',
  dss: 'DSS',
  dsf: 'DSF',
  proficiency: '熟练',
  athletics: '运动',
  acrobatics: '体操',
  sleightofhand: '巧手',
  stealth: '隐匿',
  investigation: '调查',
  arcana: '奥秘',
  history: '历史',
  nature: '自然',
  religion: '宗教',
  perception: '察觉',
  insight: '洞悉',
  animalhandling: '驯兽',
  medicine: '医药',
  survival: '求生',
  persuasion: '游说',
  deception: '欺瞒',
  intimidation: '威吓',
  performance: '表演',
};

export function parseAttributeAssignments(text: string): readonly AttributeAssignment[] {
  return Array.from(text.matchAll(attributeAssignmentPattern), (match) => ({
    name: match[1] ?? '',
    operator: (match[2] ?? '') as AttributeAssignmentOperator,
    expression: match[3] ?? '',
  })).filter((assignment) => assignment.name.length > 0 && assignment.expression.length > 0);
}

export function normalizeAttributeName(ruleSet: string, name: string): string {
  const trimmedName = name.trim();
  const normalizedRuleSet = ruleSet.toLowerCase();
  if (normalizedRuleSet === 'coc7') {
    return coc7AttributeAliases[trimmedName.toLowerCase()] ?? trimmedName;
  }
  if (normalizedRuleSet === 'dnd5e') {
    const lookupKey = trimmedName.toLowerCase().replaceAll(/[\s_-]/gu, '');
    return dnd5eAttributeAliases[lookupKey] ?? trimmedName;
  }
  return trimmedName;
}
